### ISSUE TITLE
Created items are unusable

### ISSUE THREAD

**Issue by pcastellazzi** [psiberx/cp2077-respector#2]
Hi, 

I am trying to create a legendary M251S Ajax using Quick Tweaks.
The item is created successfully in all cases, but I can't equip it because my character does not have the perk Edgerunner Artisan (Allows you to craft legendary items).
I think this is related to `Spawned weapons now get all stats as from crafting` mentioned on the release notes.

May be we can detect the right item (crafted, non-crafted) by checking the player's perks and recipes while on balanced mode, and to remove all requirements on unlimited mode.

Ty.

**Comment by psiberx** [comment]
Regular items: Yes, crafted version is preferred because only crafted version receives all random stats and bonuses when spawned. 
Iconic items: Depends on the original. Some you get as a world spawn, and some are only craftable (like Moron Labe, it's impossible to find it in the world). So there are no alternatives.

Removing the requirements means disabling them for the whole game. It's not possible to disable requirements for a single item without overriding game logic. I know how to do it, but changing the game logic just doesn't fit this mod.

One possible solution is to give an option to select which version you want to spawn. But again this will work only for regular items. Many iconic items only have a crafted version.

Let me know if you have any ideas that don't require game logic changes.

**Comment by pcastellazzi** [comment]
I think an option to get the world spawn should be enough. If you are using something like respector you probably know what you are doing.

About disabling requirements. It looks like it is possible to do it on an item by item basis.
If I understood correctly this does it:

https://github.com/PavulonTwist/cyberpunk2077-no-equip-requirements/blob/main/bin/x64/plugins/cyber_engine_tweaks/mods/no_equip_req/init.lua

**Comment by psiberx** [comment]
This modifies database about items types (not the items themselves), i.e. it affects every item instance in the game.
